"""multi provider llm layer

Revision ID: 03f23e4329f9
Revises: e4f2eac05ae1
Create Date: 2026-09-15 09:32:06.066587
"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy as sa

revision: str = '03f23e4329f9'
down_revision: Union[str, None] = 'e4f2eac05ae1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llm_provider_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('base_url', sa.String(length=400), nullable=False),
    sa.Column('default_model', sa.String(length=200), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('max_tokens', sa.Integer(), nullable=False),
    sa.Column('timeout_seconds', sa.Integer(), nullable=False),
    sa.Column('retries', sa.Integer(), nullable=False),
    sa.Column('has_api_key', sa.Boolean(), nullable=False),
    sa.Column('api_key_last_four', sa.String(length=8), nullable=False),
    sa.Column('extra_config_json', sa.JSON(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_id', name='uq_llm_provider_id')
    )
    with op.batch_alter_table('llm_provider_configs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_llm_provider_configs_enabled'), ['enabled'], unique=False)
        batch_op.create_index(batch_op.f('ix_llm_provider_configs_is_default'), ['is_default'], unique=False)
        batch_op.create_index(batch_op.f('ix_llm_provider_configs_provider_id'), ['provider_id'], unique=False)

    op.create_table('task_model_routes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task', sa.String(length=64), nullable=False),
    sa.Column('provider_config_id', sa.Integer(), nullable=True),
    sa.Column('model', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['provider_config_id'], ['llm_provider_configs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task', name='uq_task_route')
    )
    with op.batch_alter_table('task_model_routes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task_model_routes_provider_config_id'), ['provider_config_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_model_routes_task'), ['task'], unique=False)

    with op.batch_alter_table('llm_usage', schema=None) as batch_op:
        batch_op.add_column(sa.Column('provider_id', sa.String(length=64), nullable=False))
        batch_op.create_index(batch_op.f('ix_llm_usage_provider_id'), ['provider_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('llm_usage', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_llm_usage_provider_id'))
        batch_op.drop_column('provider_id')

    with op.batch_alter_table('task_model_routes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_model_routes_task'))
        batch_op.drop_index(batch_op.f('ix_task_model_routes_provider_config_id'))

    op.drop_table('task_model_routes')
    with op.batch_alter_table('llm_provider_configs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_llm_provider_configs_provider_id'))
        batch_op.drop_index(batch_op.f('ix_llm_provider_configs_is_default'))
        batch_op.drop_index(batch_op.f('ix_llm_provider_configs_enabled'))

    op.drop_table('llm_provider_configs')
    # ### end Alembic commands ###
