"""initial schema

Revision ID: e4f2eac05ae1
Revises: 
Create Date: 2026-09-15 09:02:57.962201
"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy as sa

revision: str = 'e4f2eac05ae1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('monitor_modules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('lookback_days', sa.Integer(), nullable=False),
    sa.Column('max_candidates', sa.Integer(), nullable=False),
    sa.Column('max_report_items', sa.Integer(), nullable=False),
    sa.Column('analysis_prompt', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('monitor_modules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_monitor_modules_archived'), ['archived'], unique=False)
        batch_op.create_index(batch_op.f('ix_monitor_modules_enabled'), ['enabled'], unique=False)
        batch_op.create_index(batch_op.f('ix_monitor_modules_key'), ['key'], unique=True)
        batch_op.create_index(batch_op.f('ix_monitor_modules_sort_order'), ['sort_order'], unique=False)

    op.create_table('monitoring_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('stage', sa.String(length=64), nullable=False),
    sa.Column('trigger_type', sa.String(length=16), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('total_candidates', sa.Integer(), nullable=False),
    sa.Column('total_articles', sa.Integer(), nullable=False),
    sa.Column('total_events', sa.Integer(), nullable=False),
    sa.Column('total_new_events', sa.Integer(), nullable=False),
    sa.Column('total_updated_events', sa.Integer(), nullable=False),
    sa.Column('total_report_items', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=False),
    sa.Column('cancel_requested', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('monitoring_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_monitoring_runs_report_date'), ['report_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_monitoring_runs_status'), ['status'], unique=False)

    op.create_table('llm_usage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=True),
    sa.Column('purpose', sa.String(length=64), nullable=False),
    sa.Column('module_id', sa.Integer(), nullable=True),
    sa.Column('topic_id', sa.Integer(), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=False),
    sa.Column('extra_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['monitoring_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('llm_usage', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_llm_usage_purpose'), ['purpose'], unique=False)
        batch_op.create_index(batch_op.f('ix_llm_usage_run_id'), ['run_id'], unique=False)

    op.create_table('module_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('module_id', sa.Integer(), nullable=False),
    sa.Column('module_name', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('collect_started_at', sa.DateTime(), nullable=True),
    sa.Column('collect_finished_at', sa.DateTime(), nullable=True),
    sa.Column('analysis_started_at', sa.DateTime(), nullable=True),
    sa.Column('analysis_finished_at', sa.DateTime(), nullable=True),
    sa.Column('candidate_count', sa.Integer(), nullable=False),
    sa.Column('article_count', sa.Integer(), nullable=False),
    sa.Column('selected_count', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['module_id'], ['monitor_modules.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['monitoring_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('module_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_module_runs_module_id'), ['module_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_module_runs_run_id'), ['run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_module_runs_status'), ['status'], unique=False)

    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('headline_json', sa.JSON(), nullable=True),
    sa.Column('trends_json', sa.JSON(), nullable=True),
    sa.Column('metrics_json', sa.JSON(), nullable=True),
    sa.Column('html_path', sa.Text(), nullable=False),
    sa.Column('json_path', sa.Text(), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('legacy_import', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['monitoring_runs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', name='uq_report_run')
    )
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reports_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_reports_report_date'), ['report_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_reports_run_id'), ['run_id'], unique=False)

    op.create_table('run_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('level', sa.String(length=16), nullable=False),
    sa.Column('module_key', sa.String(length=64), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['monitoring_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('run_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_run_logs_run_id'), ['run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_run_logs_timestamp'), ['timestamp'], unique=False)

    op.create_table('topics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('module_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('analysis_prompt', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['module_id'], ['monitor_modules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('module_id', 'name', name='uq_topic_module_name')
    )
    with op.batch_alter_table('topics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_topics_archived'), ['archived'], unique=False)
        batch_op.create_index(batch_op.f('ix_topics_enabled'), ['enabled'], unique=False)
        batch_op.create_index(batch_op.f('ix_topics_module_id'), ['module_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_topics_sort_order'), ['sort_order'], unique=False)

    op.create_table('excluded_keywords',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('module_id', sa.Integer(), nullable=True),
    sa.Column('topic_id', sa.Integer(), nullable=True),
    sa.Column('keyword', sa.String(length=200), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['module_id'], ['monitor_modules.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('excluded_keywords', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_excluded_keywords_keyword'), ['keyword'], unique=False)
        batch_op.create_index(batch_op.f('ix_excluded_keywords_module_id'), ['module_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_excluded_keywords_topic_id'), ['topic_id'], unique=False)

    op.create_table('intelligence_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_key', sa.String(length=160), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('module_id', sa.Integer(), nullable=True),
    sa.Column('topic_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.Column('first_seen_date', sa.Date(), nullable=True),
    sa.Column('last_seen_date', sa.Date(), nullable=True),
    sa.Column('observation_count', sa.Integer(), nullable=False),
    sa.Column('legacy_import', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['module_id'], ['monitor_modules.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_key', name='uq_event_key')
    )
    with op.batch_alter_table('intelligence_events', schema=None) as batch_op:
        batch_op.create_index('ix_event_module_status', ['module_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_intelligence_events_event_key'), ['event_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_intelligence_events_first_seen_at'), ['first_seen_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_intelligence_events_last_seen_at'), ['last_seen_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_intelligence_events_last_seen_date'), ['last_seen_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_intelligence_events_module_id'), ['module_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_intelligence_events_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_intelligence_events_topic_id'), ['topic_id'], unique=False)

    op.create_table('preferred_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('module_id', sa.Integer(), nullable=True),
    sa.Column('topic_id', sa.Integer(), nullable=True),
    sa.Column('domain', sa.String(length=200), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['module_id'], ['monitor_modules.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('preferred_sources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_preferred_sources_domain'), ['domain'], unique=False)
        batch_op.create_index(batch_op.f('ix_preferred_sources_module_id'), ['module_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_preferred_sources_topic_id'), ['topic_id'], unique=False)

    op.create_table('raw_articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('canonical_url', sa.Text(), nullable=False),
    sa.Column('url_hash', sa.String(length=64), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=300), nullable=False),
    sa.Column('domain', sa.String(length=200), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('published_raw', sa.String(length=120), nullable=False),
    sa.Column('collected_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.Column('snippet', sa.Text(), nullable=False),
    sa.Column('body_text', sa.Text(), nullable=False),
    sa.Column('language', sa.String(length=16), nullable=False),
    sa.Column('trust_score', sa.Float(), nullable=False),
    sa.Column('collector', sa.String(length=32), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=True),
    sa.Column('module_id', sa.Integer(), nullable=True),
    sa.Column('run_id', sa.Integer(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['module_id'], ['monitor_modules.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['run_id'], ['monitoring_runs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('raw_articles', schema=None) as batch_op:
        batch_op.create_index('ix_raw_articles_collected', ['collected_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_raw_articles_content_hash'), ['content_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_raw_articles_domain'), ['domain'], unique=False)
        batch_op.create_index(batch_op.f('ix_raw_articles_module_id'), ['module_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_raw_articles_run_id'), ['run_id'], unique=False)
        batch_op.create_index('ix_raw_articles_topic_date', ['topic_id', 'collected_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_raw_articles_topic_id'), ['topic_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_raw_articles_trust_score'), ['trust_score'], unique=False)
        batch_op.create_index(batch_op.f('ix_raw_articles_url_hash'), ['url_hash'], unique=True)

    op.create_table('report_sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('module_id', sa.Integer(), nullable=True),
    sa.Column('module_key', sa.String(length=64), nullable=False),
    sa.Column('module_name', sa.String(length=200), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('metrics_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['module_id'], ['monitor_modules.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('report_sections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_report_sections_module_id'), ['module_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_report_sections_report_id'), ['report_id'], unique=False)

    op.create_table('search_queries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('last_run_at', sa.DateTime(), nullable=True),
    sa.Column('last_result_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('search_queries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_search_queries_enabled'), ['enabled'], unique=False)
        batch_op.create_index(batch_op.f('ix_search_queries_topic_id'), ['topic_id'], unique=False)

    op.create_table('event_observations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=True),
    sa.Column('observation_date', sa.Date(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('tag', sa.String(length=64), nullable=False),
    sa.Column('fact_summary', sa.Text(), nullable=False),
    sa.Column('assessment', sa.Text(), nullable=False),
    sa.Column('importance', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.String(length=16), nullable=False),
    sa.Column('structured_data_json', sa.JSON(), nullable=True),
    sa.Column('is_correction', sa.Boolean(), nullable=False),
    sa.Column('legacy_import', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['intelligence_events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['monitoring_runs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('event_observations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_event_observations_event_id'), ['event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_observations_observation_date'), ['observation_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_observations_run_id'), ['run_id'], unique=False)
        batch_op.create_index('ix_obs_event_date', ['event_id', 'observation_date'], unique=False)

    op.create_table('observation_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('observation_id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('relevance', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['raw_articles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['observation_id'], ['event_observations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('observation_id', 'article_id', name='uq_obs_article')
    )
    with op.batch_alter_table('observation_sources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_observation_sources_article_id'), ['article_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_observation_sources_observation_id'), ['observation_id'], unique=False)

    op.create_table('report_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_section_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('observation_id', sa.Integer(), nullable=True),
    sa.Column('tag', sa.String(length=64), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('fact_summary', sa.Text(), nullable=False),
    sa.Column('assessment', sa.Text(), nullable=False),
    sa.Column('importance', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.String(length=16), nullable=False),
    sa.Column('event_state', sa.String(length=16), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['intelligence_events.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['observation_id'], ['event_observations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['report_section_id'], ['report_sections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('report_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_report_items_event_id'), ['event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_report_items_observation_id'), ['observation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_report_items_report_section_id'), ['report_section_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_report_items_report_section_id'))
        batch_op.drop_index(batch_op.f('ix_report_items_observation_id'))
        batch_op.drop_index(batch_op.f('ix_report_items_event_id'))

    op.drop_table('report_items')
    with op.batch_alter_table('observation_sources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_observation_sources_observation_id'))
        batch_op.drop_index(batch_op.f('ix_observation_sources_article_id'))

    op.drop_table('observation_sources')
    with op.batch_alter_table('event_observations', schema=None) as batch_op:
        batch_op.drop_index('ix_obs_event_date')
        batch_op.drop_index(batch_op.f('ix_event_observations_run_id'))
        batch_op.drop_index(batch_op.f('ix_event_observations_observation_date'))
        batch_op.drop_index(batch_op.f('ix_event_observations_event_id'))

    op.drop_table('event_observations')
    with op.batch_alter_table('search_queries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_search_queries_topic_id'))
        batch_op.drop_index(batch_op.f('ix_search_queries_enabled'))

    op.drop_table('search_queries')
    with op.batch_alter_table('report_sections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_report_sections_report_id'))
        batch_op.drop_index(batch_op.f('ix_report_sections_module_id'))

    op.drop_table('report_sections')
    with op.batch_alter_table('raw_articles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_raw_articles_url_hash'))
        batch_op.drop_index(batch_op.f('ix_raw_articles_trust_score'))
        batch_op.drop_index(batch_op.f('ix_raw_articles_topic_id'))
        batch_op.drop_index('ix_raw_articles_topic_date')
        batch_op.drop_index(batch_op.f('ix_raw_articles_run_id'))
        batch_op.drop_index(batch_op.f('ix_raw_articles_module_id'))
        batch_op.drop_index(batch_op.f('ix_raw_articles_domain'))
        batch_op.drop_index(batch_op.f('ix_raw_articles_content_hash'))
        batch_op.drop_index('ix_raw_articles_collected')

    op.drop_table('raw_articles')
    with op.batch_alter_table('preferred_sources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_preferred_sources_topic_id'))
        batch_op.drop_index(batch_op.f('ix_preferred_sources_module_id'))
        batch_op.drop_index(batch_op.f('ix_preferred_sources_domain'))

    op.drop_table('preferred_sources')
    with op.batch_alter_table('intelligence_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_intelligence_events_topic_id'))
        batch_op.drop_index(batch_op.f('ix_intelligence_events_status'))
        batch_op.drop_index(batch_op.f('ix_intelligence_events_module_id'))
        batch_op.drop_index(batch_op.f('ix_intelligence_events_last_seen_date'))
        batch_op.drop_index(batch_op.f('ix_intelligence_events_last_seen_at'))
        batch_op.drop_index(batch_op.f('ix_intelligence_events_first_seen_at'))
        batch_op.drop_index(batch_op.f('ix_intelligence_events_event_key'))
        batch_op.drop_index('ix_event_module_status')

    op.drop_table('intelligence_events')
    with op.batch_alter_table('excluded_keywords', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_excluded_keywords_topic_id'))
        batch_op.drop_index(batch_op.f('ix_excluded_keywords_module_id'))
        batch_op.drop_index(batch_op.f('ix_excluded_keywords_keyword'))

    op.drop_table('excluded_keywords')
    with op.batch_alter_table('topics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_topics_sort_order'))
        batch_op.drop_index(batch_op.f('ix_topics_module_id'))
        batch_op.drop_index(batch_op.f('ix_topics_enabled'))
        batch_op.drop_index(batch_op.f('ix_topics_archived'))

    op.drop_table('topics')
    with op.batch_alter_table('run_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_run_logs_timestamp'))
        batch_op.drop_index(batch_op.f('ix_run_logs_run_id'))

    op.drop_table('run_logs')
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reports_run_id'))
        batch_op.drop_index(batch_op.f('ix_reports_report_date'))
        batch_op.drop_index(batch_op.f('ix_reports_created_at'))

    op.drop_table('reports')
    with op.batch_alter_table('module_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_module_runs_status'))
        batch_op.drop_index(batch_op.f('ix_module_runs_run_id'))
        batch_op.drop_index(batch_op.f('ix_module_runs_module_id'))

    op.drop_table('module_runs')
    with op.batch_alter_table('llm_usage', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_llm_usage_run_id'))
        batch_op.drop_index(batch_op.f('ix_llm_usage_purpose'))

    op.drop_table('llm_usage')
    with op.batch_alter_table('monitoring_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_monitoring_runs_status'))
        batch_op.drop_index(batch_op.f('ix_monitoring_runs_report_date'))

    op.drop_table('monitoring_runs')
    with op.batch_alter_table('monitor_modules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_monitor_modules_sort_order'))
        batch_op.drop_index(batch_op.f('ix_monitor_modules_key'))
        batch_op.drop_index(batch_op.f('ix_monitor_modules_enabled'))
        batch_op.drop_index(batch_op.f('ix_monitor_modules_archived'))

    op.drop_table('monitor_modules')
    op.drop_table('app_settings')
    # ### end Alembic commands ###
